version: "3.7"

services:
  spigot:
    build:
      context: .
    tty: true
    stdin_open: true
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
      - "25565:25565"
    volumes:
      - type: bind
        source: "./minecraft"
        target: "/mc"
