---
# tasks file for huitcraft
- name: All packages upgrade
  apt:
    update_cache: yes
    upgrade: yes
    become: yes

- name: Packages install
  apt:
    name:
      - vim
      - curl
      - git
      - docker
      - docker-compose
    state: latest
    become: yes

- name: Add minecraft user
  user:
    name: minecraft
    become: yes

- name: Install rootless docker
  shell: curl -fsSL https://get.docker.com/rootless | sh
  become: yes
  become_user: minecraft

- name: Send .bashrc
  src: ../files/.bashrc_ubuntu
  dest: /home/minecraft/.bashrc
  owner: minecraft
  group: minecraft
  become: yes
  become_user: minecraft

- name: Git clone huitcraft
  git:
    repo: https://github.com/HUITGroup/huitcraft.git
    dest: /home/minecraft
    become: yes
    become_user: minecraft

- name: Start spigot container
  command: docker-compose up -d chdir=/home/minecraft/huitcraft
  become: yes
  become_user: minecraft
